name: Test

on:
  push:
    branches: ["master"]
    paths:
      - '**.js'
  pull_request:
    branches: ["master"]
    paths:
      - '**.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm run test
